linters:
  disable-all: true
  enable:
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - Prefix(github.com/javierdelapuente/app-charm-config)
issues:
  # these values ensure that all issues will be surfaced
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m

